base_url = "https://marcodpt.github.io/zolastrap/"

default_language = "en"
compile_sass = true
title = "Zolastrap"
description = "A Bootstrap theme for Zola"
generate_feed = false
output_dir = "docs"

taxonomies = [
		{name = "tags", paginate_by = 5},
		{name = "authors", paginate_by = 5},
]

[markdown]
highlight_code = true

[extra]
zolastrap_navbar_links = [
	{title = 'Articles', link = 'articles', external = false},
  {title = 'Authors', link = 'authors', external = false},
  {title = 'Tags', link = 'tags', external = false},
	{title = 'About', link = 'about', external = false},
]
zolastrap_navbar_search = 'Search'
zolastrap_date_format = '%d/%m/%Y'
