base_url = "https://marcodpt.github.io/zolastrap/"

default_language = "en"
compile_sass = true
title = "Zolastrap"
description = "A Bootstrap theme for Zola"
generate_feed = false
output_dir = "docs"

taxonomies = [
		{name = "tags", paginate_by = 5},
		{name = "authors", paginate_by = 5},
]

[markdown]
highlight_code = true

[extra]
zolastrap_theme = 'simplex'
zolastrap_navbar_links = [
	{title = 'Articles', link = 'articles', external = false},
  {title = 'Authors', link = 'authors', external = false},
	{title = 'About', link = 'about', external = false},
	{title = 'Topics', link = 'tags', external = false},
	{title = 'Github', link = 'https://github.com/marcodpt/zolastrap', external = true},
]
zolastrap_navbar_search = 'Search'
zolastrap_navbar_themes = true
zolastrap_date_format = '%d/%m/%Y'
zolastrap_home = [
  [
    {section = 'articles', size = 8, start = 0, end = 4, type = 'default'},
    {section = 'articles', size = 4, start = 4, end = 12, type = 'horizontal', title = 'blog'}
  ],
  [
    {section = 'articles', size = 6, start = 10, end = 14, type = 'vertical', title = 'media'}
  ]
]

zolastrap_tags = 'Posts by Topics'
zolastrap_themes = [
  'default',
  'cerulean',
  'cosmo',
  'cyborg',
  'darkly',
  'flatly',
  'journal',
  'litera',
  'lumen',
  'lux',
  'materia',
  'minty',
  'morph',
  'pulse',
  'quartz',
  'sandstone',
  'simplex',
  'sketchy',
  'slate',
  'solar',
  'spacelab',
  'superhero',
  'united',
  'vapor',
  'yeti',
  'zephyr'
]
