base_url = "https://marcodpt.github.io/zolastrap/"

default_language = "en"
compile_sass = true
title = "Zolastrap"
description = "A Bootstrap theme for Zola"
generate_feed = false
output_dir = "docs"

taxonomies = [
		{name = "tags", paginate_by = 5},
		{name = "authors", paginate_by = 5},
]

[markdown]
highlight_code = true

[extra]
navbar = [
	{title = 'Articles', url = 'articles'},
  {title = 'Authors', url = 'authors'},
	{title = 'About', url = 'about'},
	{title = 'Topics', url = 'tags'},
	{title = 'Github', url = 'https://github.com/marcodpt/zolastrap'},
]
date_format = '%d/%m/%Y'
search = 'Search'
theme = 'simplex'
tags = 'Posts by Topics'
themes = [
  'default',
  'cerulean',
  'cosmo',
  'cyborg',
  'darkly',
  'flatly',
  'journal',
  'litera',
  'lumen',
  'lux',
  'materia',
  'minty',
  'morph',
  'pulse',
  'quartz',
  'sandstone',
  'simplex',
  'sketchy',
  'slate',
  'solar',
  'spacelab',
  'superhero',
  'united',
  'vapor',
  'yeti',
  'zephyr'
]
