name = "zolastrap"
description = "A bootstrap theme for zola"
license = "MIT"
homepage = "https://github.com/marcodpt/zolastrap"
min_version = "0.14.1"
demo = "https://marcodpt.github.io/zolastrap/"

[author]
name = "Marco Tomic"
homepage = "https://marcodpt.github.io"

[extra]
navbar = [
  {title = 'Authors', url = 'authors'},
	{title = 'Topics', url = 'tags'},
]
date_format = '%d/%m/%Y'
search = 'Search'
theme = 'simplex'
tags = 'Posts by Topics'
social_icons = [
  {title = 'Facebook', icon = 'facebook-f', url = 'https://www.facebook.com'},
  {title = 'Instagram', icon = 'instagram', url = 'https://www.instagram.com'},
  {title = 'Twitter', icon = 'twitter', url = 'https://twitter.com'},
  {title = 'YouTube', icon = 'youtube', url = 'https://www.youtube.com'}
]
email = "user@mail.com"
banner = "img/banner.jpeg"
footer_bg = "dark"
footer_font = "light"
navbar_bg = "dark"
navbar_type = "dark"
themes = [
  'default',
  'cerulean',
  'cosmo',
  'cyborg',
  'darkly',
  'flatly',
  'journal',
  'litera',
  'lumen',
  'lux',
  'materia',
  'minty',
  'morph',
  'pulse',
  'quartz',
  'sandstone',
  'simplex',
  'sketchy',
  'slate',
  'solar',
  'spacelab',
  'superhero',
  'united',
  'vapor',
  'yeti',
  'zephyr'
]
schemes = [
  'dark',
  'light',
  'primary dark',
  'primary light',
  'secondary dark',
  'secondary light',
  'success dark',
  'success light',
  'danger dark',
  'danger light',
  'warning dark',
  'warning light',
  'info dark',
  'info light',
]
